### PR TITLE
Reorganizing repository structure

### PR DESCRIPTION
**Pull request by ariscahyadi**
@smartx-usman and @NattVi ... I re-organized the backend directory.
Please check and merge if everything is fine.

### CODE REVIEW

**Comment by ariscahyadi** [comment]
Hi @NattVi ... please check your README markdown https://github.com/OFTEIN-NET/OFTEIN-MultiTenantPortal/blob/organizing-repo-structure/backend-app/README.md
Please a simple GitHub markdown.

**Comment by smartx-usman** [comment]
@ariscahyadi thanks, reorganization looks good to me. @NattVi One minor fix is to give correct path to images in README because images are not displayed. Remove / before /pics in image tag.

**Comment by smartx-usman** [comment]
Merging PR but still markdown need to be fixed by @NattVi.

**Review by smartx-usman — APPROVED** [review]
Everything seems okay except markdown that need to be fixed by @NattVi. Thanks!

**Pull request merged**
